on:
  pull_request_target:
    branches: ["main"]

jobs:
  tests:
    name: Run Tests
    uses: is-itmo-c-25/cicd-workflows-test/.github/workflows/tests.yml@main
    with:
      runs-on: itmogus
      platforms: |
        [
          {
            "id": "clang",
            "name": "clang",
            "compiler": "clang++-19",
            "flags": ""
          },
          {
            "id": "clang_san",
            "name": "clang (san)",
            "compiler": "clang++-19",
            "flags": "-fsanitize=address,undefined"
          }
        ]

  quality:
    name: Quality
    uses: is-itmo-c-25/cicd-workflows-test/.github/workflows/quality.yml@main
    with:
      runs-on: itmogus
      coverage: false
      tidy-config: |
        Checks:
          -*,
          bugprone-misplaced-widening-cast,
          bugprone-redundant-branch-condition,
          bugprone-suspicious-include,
          llvm-namespace-comment,
          misc-header-include-cycle,
          misc-include-cleaner,
          readability-delete-null-pointer,
          readability-identifier-naming,
          readability-misleading-indentation,
          readability-redundant-control-flow,
          readability-static-accessed-through-instance,

        CheckOptions:
          - { key: readability-identifier-naming.NamespaceCase,            value: lower_case }
          - { key: readability-identifier-naming.ClassCase,                value: CamelCase  }
          - { key: readability-identifier-naming.StructCase,               value: CamelCase  }
          - { key: readability-identifier-naming.TemplateParameterCase,    value: CamelCase  }
          - { key: readability-identifier-naming.FunctionCase,             value: CamelCase  }
          - { key: readability-identifier-naming.VariableCase,             value: lower_case }
          - { key: readability-identifier-naming.ClassMemberCase,          value: lower_case }
          - { key: readability-identifier-naming.ClassMemberSuffix,        value: _          }
          - { key: readability-identifier-naming.PrivateMemberSuffix,      value: _          }
          - { key: readability-identifier-naming.ProtectedMemberSuffix,    value: _          }
          - { key: readability-identifier-naming.EnumConstantCase,         value: CamelCase  }
          - { key: readability-identifier-naming.EnumConstantPrefix,       value: k          }
          - { key: readability-identifier-naming.ConstexprVariableCase,    value: CamelCase  }
          - { key: readability-identifier-naming.ConstexprVariablePrefix,  value: k          }
          - { key: readability-identifier-naming.GlobalConstantCase,       value: CamelCase  }
          - { key: readability-identifier-naming.GlobalConstantPrefix,     value: k          }
          - { key: readability-identifier-naming.MemberConstantCase,       value: CamelCase  }
          - { key: readability-identifier-naming.MemberConstantPrefix,     value: k          }
          - { key: readability-identifier-naming.StaticConstantCase,       value: CamelCase  }
          - { key: readability-identifier-naming.StaticConstantPrefix,     value: k          }

  report:
    name: Report
    if: ${{ !cancelled() }}
    permissions:
      pull-requests: write
    uses: is-itmo-c-25/cicd-workflows-test/.github/workflows/report.yml@main
    needs: [ tests, quality ]
    with:
      runs-on: itmogus
      config: |
        {
          "tests": {
            "platforms": {
              "clang": "<code>clang</code>",
              "clang_san": "<code>clang-san</code>"
            }
          },
          "coverage": {
            "levels": [0, 50, 75, 90]
          },
          "codestyle": {
            "levels": [9, 6, 3, 0]
          }
        }

      tests: ${{ needs.tests.outputs.results }}
      codestyle: ${{ needs.quality.outputs.codestyle }}
      coverage: ${{ needs.quality.outputs.coverage }}
